#include "ProfileStore.h"
#include "AppPaths.h"

#include <QSettings>
#include <QCoreApplication>
#include <QJsonDocument>
#include <QJsonArray>
#include <QJsonObject>
#include <QUuid>
#include <QHash>
#include <QLoggingCategory>

static QSettings& store()
{
    static QSettings s(AppPaths::dataDir() + QStringLiteral("/mymediavault.ini"),
                       QSettings::IniFormat);
    return s;
}

static void save(const QVector<Profile>& items); // defined below; used by migrateIcons()

// ---- Legacy profile-icon mojibake repair -------------------------------------------------------------------
// Pre-existing (B2-era) builds round-tripped the profile-icon emoji through a Windows-1252 mis-decode: the
// UTF-8 icon bytes in mymediavault.ini were read back with the local 8-bit codec and re-written as UTF-8,
// TWICE across the app's history. The dog emoji "🐶" (UTF-8 F0 9F 90 B6) thus ended up stored as the byte
// sequence C3 83 C2 B0 C3 85 C2 B8 C3 82 C2 90 C3 82 C2 B6 — rendered as "Ã°Å¸ÂÂ¶" mojibake in every surface
// that reads ProfileStore (classic and themed alike). Current code encodes/round-trips emoji correctly, so this
// only affects DATA already on disk. We repair on read (display is always correct) and persist once via
// migrateIcons() (see main.cpp). The table maps the exact corrupted UTF-8 (single- AND double-mis-decode
// depth) of the shipped icon set back to the intended emoji; ANY value not on this list is left untouched.
static const QHash<QString, QString>& mojibakeRepairTable()
{
    static const QHash<QString, QString> table = [] {
        // { corrupted-UTF-8 hex, intended-emoji UTF-8 hex } for the shipped kProfileIcons set + the "🙂"
        // fallback. Generated by replaying the historical Windows-1252-decode + UTF-8-encode corruption.
        static const char* const kPairs[][2] = {
            { "c3b0c5b8c290c2b1", "f09f90b1" }, { "c383c2b0c385c2b8c382c290c382c2b1", "f09f90b1" }, // 🐱
            { "c3b0c5b8c290c2b6", "f09f90b6" }, { "c383c2b0c385c2b8c382c290c382c2b6", "f09f90b6" }, // 🐶
            { "c3b0c5b8c2a6c5a0", "f09fa68a" }, { "c383c2b0c385c2b8c382c2a6c385c2a0", "f09fa68a" }, // 🦊
            { "c3b0c5b8c290c2bc", "f09f90bc" }, { "c383c2b0c385c2b8c382c290c382c2bc", "f09f90bc" }, // 🐼
            { "c3b0c5b8c290c2b8", "f09f90b8" }, { "c383c2b0c385c2b8c382c290c382c2b8", "f09f90b8" }, // 🐸
            { "c3b0c5b8c290c2b5", "f09f90b5" }, { "c383c2b0c385c2b8c382c290c382c2b5", "f09f90b5" }, // 🐵
            { "c3b0c5b8c2a6e2809e", "f09fa684" }, { "c383c2b0c385c2b8c382c2a6c3a2e282acc5be", "f09fa684" }, // 🦄
            { "c3b0c5b8c2a4e28093", "f09fa496" }, { "c383c2b0c385c2b8c382c2a4c3a2e282ace2809c", "f09fa496" }, // 🤖
            { "c3b0c5b8e28098c2be", "f09f91be" }, { "c383c2b0c385c2b8c3a2e282accb9cc382c2be", "f09f91be" }, // 👾
            { "c3b0c5b8c290e284a2", "f09f9099" }, { "c383c2b0c385c2b8c382c290c3a2e2809ec2a2", "f09f9099" }, // 🐙
            { "c3b0c5b8c290c2af", "f09f90af" }, { "c383c2b0c385c2b8c382c290c382c2af", "f09f90af" }, // 🐯
            { "c3b0c5b8c2a6e280b0", "f09fa689" }, { "c383c2b0c385c2b8c382c2a6c3a2e282acc2b0", "f09fa689" }, // 🦉
            { "c3b0c5b8c290c2a7", "f09f90a7" }, { "c383c2b0c385c2b8c382c290c382c2a7", "f09f90a7" }, // 🐧
            { "c3b0c5b8c290c2a8", "f09f90a8" }, { "c383c2b0c385c2b8c382c290c382c2a8", "f09f90a8" }, // 🐨
            { "c3b0c5b8c2a6c281", "f09fa681" }, { "c383c2b0c385c2b8c382c2a6c382c281", "f09fa681" }, // 🦁
            { "c3b0c5b8c290c2b0", "f09f90b0" }, { "c383c2b0c385c2b8c382c290c382c2b0", "f09f90b0" }, // 🐰
            { "c3b0c5b8c290c29d", "f09f909d" }, { "c383c2b0c385c2b8c382c290c382c29d", "f09f909d" }, // 🐝
            { "c3b0c5b8c2a6e28093", "f09fa696" }, { "c383c2b0c385c2b8c382c2a6c3a2e282ace2809c", "f09fa696" }, // 🦖
            { "c3b0c5b8c290c2a2", "f09f90a2" }, { "c383c2b0c385c2b8c382c290c382c2a2", "f09f90a2" }, // 🐢
            { "c3b0c5b8c28de2809e", "f09f8d84" }, { "c383c2b0c385c2b8c382c28dc3a2e282acc5be", "f09f8d84" }, // 🍄
            { "c3a2c2adc290", "e2ad90" }, { "c383c2a2c382c2adc382c290", "e2ad90" }, // ⭐
            { "c3b0c5b8c592cb86", "f09f8c88" }, { "c383c2b0c385c2b8c385e28099c38be280a0", "f09f8c88" }, // 🌈
            { "c3b0c5b8c28de282ac", "f09f8d80" }, { "c383c2b0c385c2b8c382c28dc3a2e2809ac2ac", "f09f8d80" }, // 🍀
            { "c3b0c5b8c5bdc2ae", "f09f8eae" }, { "c383c2b0c385c2b8c385c2bdc382c2ae", "f09f8eae" }, // 🎮
            { "c3b0c5b8e284a2e2809a", "f09f9982" }, { "c383c2b0c385c2b8c3a2e2809ec2a2c3a2e282acc5a1", "f09f9982" }, // 🙂
        };
        QHash<QString, QString> t;
        for (const auto& pr : kPairs)
        {
            const QString corrupt = QString::fromUtf8(QByteArray::fromHex(pr[0]));
            const QString emoji   = QString::fromUtf8(QByteArray::fromHex(pr[1]));
            t.insert(corrupt, emoji);
        }
        return t;
    }();
    return table;
}

// Returns the intended emoji if `icon` is a known legacy-mojibake corruption of a shipped icon; otherwise
// returns `icon` unchanged (unrecognized/custom values are never altered).
static QString repairMojibakeIcon(const QString& icon)
{
    return mojibakeRepairTable().value(icon, icon);
}

QVector<Profile> ProfileStore::list()
{
    QVector<Profile> out;
    const QByteArray json = store().value(QStringLiteral("profiles/list")).toString().toUtf8();
    for (const QJsonValue& v : QJsonDocument::fromJson(json).array())
    {
        if (!v.isObject()) continue;
        const QJsonObject o = v.toObject();
        Profile p;
        p.id   = o.value(QStringLiteral("id")).toString();
        p.name = o.value(QStringLiteral("name")).toString();
        p.icon = repairMojibakeIcon(o.value(QStringLiteral("icon")).toString()); // legacy mojibake -> emoji
        p.restricted = o.value(QStringLiteral("restricted")).toBool();
        if (!p.id.isEmpty()) out.push_back(p);
    }
    return out;
}

void ProfileStore::migrateIcons()
{
    // One-time: rewrite any stored icon that is a known legacy mojibake corruption. list() already returns the
    // repaired icon, and save() persists whatever list() yields, so a single save() cleans the ini in place.
    // We only write when something actually changed, keeping the ini byte-identical for uncorrupted installs.
    const QByteArray json = store().value(QStringLiteral("profiles/list")).toString().toUtf8();
    bool changed = false;
    for (const QJsonValue& v : QJsonDocument::fromJson(json).array())
    {
        if (!v.isObject()) continue;
        const QString stored = v.toObject().value(QStringLiteral("icon")).toString();
        if (repairMojibakeIcon(stored) != stored) { changed = true; break; }
    }
    if (!changed) return;
    save(list()); // list() repairs; save() rewrites the JSON with corrected icons
    qInfo("ProfileStore: repaired legacy mojibake profile icon(s) in mymediavault.ini");
}

static void save(const QVector<Profile>& items)
{
    QJsonArray arr;
    for (const Profile& p : items)
    {
        QJsonObject o;
        o.insert(QStringLiteral("id"), p.id);
        o.insert(QStringLiteral("name"), p.name);
        o.insert(QStringLiteral("icon"), p.icon);
        o.insert(QStringLiteral("restricted"), p.restricted);
        arr.append(o);
    }
    store().setValue(QStringLiteral("profiles/list"),
                     QString::fromUtf8(QJsonDocument(arr).toJson(QJsonDocument::Compact)));
    store().sync();
}

Profile ProfileStore::add(const QString& name, const QString& icon)
{
    Profile p;
    p.id = QUuid::createUuid().toString(QUuid::WithoutBraces);
    p.name = name.trimmed().isEmpty() ? QStringLiteral("User") : name.trimmed();
    p.icon = icon.isEmpty() ? QStringLiteral("🙂") : icon;
    QVector<Profile> items = list();
    items.push_back(p);
    save(items);
    return p;
}

void ProfileStore::update(const QString& id, const QString& name, const QString& icon)
{
    QVector<Profile> items = list();
    for (Profile& p : items)
        if (p.id == id)
        {
            if (!name.trimmed().isEmpty()) p.name = name.trimmed();
            if (!icon.isEmpty())           p.icon = icon;
        }
    save(items);
}

void ProfileStore::setRestricted(const QString& id, bool restricted)
{
    QVector<Profile> items = list();
    for (Profile& p : items) if (p.id == id) p.restricted = restricted;
    save(items);
}

void ProfileStore::remove(const QString& id)
{
    QVector<Profile> items = list();
    for (int i = items.size() - 1; i >= 0; --i)
        if (items[i].id == id) items.remove(i);
    save(items);
    if (currentId() == id) setCurrent(items.isEmpty() ? QString() : items.first().id);
}

QString ProfileStore::currentId()
{
    return store().value(QStringLiteral("profiles/current")).toString();
}

void ProfileStore::setCurrent(const QString& id)
{
    store().setValue(QStringLiteral("profiles/current"), id);
    store().sync();
}

Profile ProfileStore::current()
{
    const QString id = currentId();
    for (const Profile& p : list())
        if (p.id == id) return p;
    return {};
}
